/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion;
import org.readutf.buildformat.postgres.jooq.tables.FlywaySchemaHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>build_meta</code>.
     */
    public final BuildMeta BUILD_META = BuildMeta.BUILD_META;

    /**
     * The table <code>build_supported_formats</code>.
     */
    public final BuildSupportedFormats BUILD_SUPPORTED_FORMATS = BuildSupportedFormats.BUILD_SUPPORTED_FORMATS;

    /**
     * The table <code>build_version</code>.
     */
    public final BuildVersion BUILD_VERSION = BuildVersion.BUILD_VERSION;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BuildMeta.BUILD_META,
            BuildSupportedFormats.BUILD_SUPPORTED_FORMATS,
            BuildVersion.BUILD_VERSION,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
