/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion;
import org.readutf.buildformat.postgres.jooq.tables.FlywaySchemaHistory;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_BUILD_META_NAME = Internal.createIndex(DSL.name("idx_build_meta_name"), BuildMeta.BUILD_META, new OrderField[] { BuildMeta.BUILD_META.BUILD_NAME }, true);
    public static final Index IDX_BUILD_SUPPORTED_FORMATS_VERSION_ID_FORMAT_NAME = Internal.createIndex(DSL.name("idx_build_supported_formats_version_id_format_name"), BuildSupportedFormats.BUILD_SUPPORTED_FORMATS, new OrderField[] { BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.BUILD_VERSION_ID, BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.FORMAT_NAME }, true);
    public static final Index IDX_BUILD_VERSION_META_ID_VERSION_NUMBER = Internal.createIndex(DSL.name("idx_build_version_meta_id_version_number"), BuildVersion.BUILD_VERSION, new OrderField[] { BuildVersion.BUILD_VERSION.BUILD_META_ID, BuildVersion.BUILD_VERSION.VERSION_NUMBER }, true);
}
