/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion;
import org.readutf.buildformat.postgres.jooq.tables.FlywaySchemaHistory;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildMetaRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildSupportedFormatsRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildVersionRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.FlywaySchemaHistoryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BuildMetaRecord> BUILD_META_PKEY = Internal.createUniqueKey(BuildMeta.BUILD_META, DSL.name("build_meta_pkey"), new TableField[] { BuildMeta.BUILD_META.ID }, true);
    public static final UniqueKey<BuildSupportedFormatsRecord> BUILD_SUPPORTED_FORMATS_PKEY = Internal.createUniqueKey(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS, DSL.name("build_supported_formats_pkey"), new TableField[] { BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.ID }, true);
    public static final UniqueKey<BuildVersionRecord> BUILD_VERSION_PKEY = Internal.createUniqueKey(BuildVersion.BUILD_VERSION, DSL.name("build_version_pkey"), new TableField[] { BuildVersion.BUILD_VERSION.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BuildSupportedFormatsRecord, BuildVersionRecord> BUILD_SUPPORTED_FORMATS__BUILD_SUPPORTED_FORMATS_BUILD_VERSION_ID_FKEY = Internal.createForeignKey(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS, DSL.name("build_supported_formats_build_version_id_fkey"), new TableField[] { BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.BUILD_VERSION_ID }, Keys.BUILD_VERSION_PKEY, new TableField[] { BuildVersion.BUILD_VERSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BuildVersionRecord, BuildMetaRecord> BUILD_VERSION__BUILD_VERSION_BUILD_META_ID_FKEY = Internal.createForeignKey(BuildVersion.BUILD_VERSION, DSL.name("build_version_build_meta_id_fkey"), new TableField[] { BuildVersion.BUILD_VERSION.BUILD_META_ID }, Keys.BUILD_META_PKEY, new TableField[] { BuildMeta.BUILD_META.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
