/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion;
import org.readutf.buildformat.postgres.jooq.tables.FlywaySchemaHistory;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildMetaRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildSupportedFormatsRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildVersionRecord;
import org.readutf.buildformat.postgres.jooq.tables.records.FlywaySchemaHistoryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BuildMetaRecord> BUILD_META__PK_BUILD_META = Internal.createUniqueKey(BuildMeta.BUILD_META, DSL.name("pk_build_meta"), new TableField[] { BuildMeta.BUILD_META.ID }, true);
    public static final UniqueKey<BuildSupportedFormatsRecord> BUILD_SUPPORTED_FORMATS__PK_BUILD_SUPPORTED_FORMATS = Internal.createUniqueKey(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS, DSL.name("pk_build_supported_formats"), new TableField[] { BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.ID }, true);
    public static final UniqueKey<BuildVersionRecord> BUILD_VERSION__PK_BUILD_VERSION = Internal.createUniqueKey(BuildVersion.BUILD_VERSION, DSL.name("pk_build_version"), new TableField[] { BuildVersion.BUILD_VERSION.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY__PK_FLYWAY_SCHEMA_HISTORY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BuildSupportedFormatsRecord, BuildVersionRecord> BUILD_SUPPORTED_FORMATS__FK_BUILD_SUPPORTED_FORMATS_PK_BUILD_VERSION = Internal.createForeignKey(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS, DSL.name("fk_build_supported_formats_pk_build_version"), new TableField[] { BuildSupportedFormats.BUILD_SUPPORTED_FORMATS.BUILD_VERSION_ID }, Keys.BUILD_VERSION__PK_BUILD_VERSION, new TableField[] { BuildVersion.BUILD_VERSION.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BuildVersionRecord, BuildMetaRecord> BUILD_VERSION__FK_BUILD_VERSION_PK_BUILD_META = Internal.createForeignKey(BuildVersion.BUILD_VERSION, DSL.name("fk_build_version_pk_build_meta"), new TableField[] { BuildVersion.BUILD_VERSION.BUILD_META_ID }, Keys.BUILD_META__PK_BUILD_META, new TableField[] { BuildMeta.BUILD_META.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
