/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildSupportedFormatsRecord extends UpdatableRecordImpl<BuildSupportedFormatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.build_supported_formats.id</code>.
     */
    public BuildSupportedFormatsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.build_supported_formats.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.build_supported_formats.build_version_id</code>.
     */
    public BuildSupportedFormatsRecord setBuildVersionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.build_supported_formats.build_version_id</code>.
     */
    public Integer getBuildVersionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.build_supported_formats.format_name</code>.
     */
    public BuildSupportedFormatsRecord setFormatName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.build_supported_formats.format_name</code>.
     */
    public String getFormatName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BuildSupportedFormatsRecord
     */
    public BuildSupportedFormatsRecord() {
        super(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS);
    }

    /**
     * Create a detached, initialised BuildSupportedFormatsRecord
     */
    public BuildSupportedFormatsRecord(Integer id, Integer buildVersionId, String formatName) {
        super(BuildSupportedFormats.BUILD_SUPPORTED_FORMATS);

        setId(id);
        setBuildVersionId(buildVersionId);
        setFormatName(formatName);
        resetTouchedOnNotNull();
    }
}
