/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildMetaRecord extends UpdatableRecordImpl<BuildMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>build_meta.id</code>.
     */
    public BuildMetaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>build_meta.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>build_meta.build_name</code>.
     */
    public BuildMetaRecord setBuildName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>build_meta.build_name</code>.
     */
    public String getBuildName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>build_meta.created_at</code>.
     */
    public BuildMetaRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>build_meta.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BuildMetaRecord
     */
    public BuildMetaRecord() {
        super(BuildMeta.BUILD_META);
    }

    /**
     * Create a detached, initialised BuildMetaRecord
     */
    public BuildMetaRecord(Integer id, String buildName, LocalDateTime createdAt) {
        super(BuildMeta.BUILD_META);

        setId(id);
        setBuildName(buildName);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
