/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables.records;


import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildVersionRecord extends UpdatableRecordImpl<BuildVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.build_version.id</code>.
     */
    public BuildVersionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.build_version.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.build_version.build_meta_id</code>.
     */
    public BuildVersionRecord setBuildMetaId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.build_version.build_meta_id</code>.
     */
    public Integer getBuildMetaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.build_version.version_number</code>.
     */
    public BuildVersionRecord setVersionNumber(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.build_version.version_number</code>.
     */
    public Integer getVersionNumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.build_version.checksum</code>.
     */
    public BuildVersionRecord setChecksum(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.build_version.checksum</code>.
     */
    public Integer getChecksum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.build_version.metadata</code>.
     */
    public BuildVersionRecord setMetadata(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.build_version.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BuildVersionRecord
     */
    public BuildVersionRecord() {
        super(BuildVersion.BUILD_VERSION);
    }

    /**
     * Create a detached, initialised BuildVersionRecord
     */
    public BuildVersionRecord(Integer id, Integer buildMetaId, Integer versionNumber, Integer checksum, JSONB metadata) {
        super(BuildVersion.BUILD_VERSION);

        setId(id);
        setBuildMetaId(buildMetaId);
        setVersionNumber(versionNumber);
        setChecksum(checksum);
        setMetadata(metadata);
        resetTouchedOnNotNull();
    }
}
