/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.readutf.buildformat.postgres.jooq.Indexes;
import org.readutf.buildformat.postgres.jooq.Keys;
import org.readutf.buildformat.postgres.jooq.Public;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion.BuildVersionPath;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildMetaRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildMeta extends TableImpl<BuildMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.build_meta</code>
     */
    public static final BuildMeta BUILD_META = new BuildMeta();

    /**
     * The class holding records for this typeReference
     */
    @Override
    public Class<BuildMetaRecord> getRecordType() {
        return BuildMetaRecord.class;
    }

    /**
     * The column <code>public.build_meta.id</code>.
     */
    public final TableField<BuildMetaRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.build_meta.build_name</code>.
     */
    public final TableField<BuildMetaRecord, String> BUILD_NAME = createField(DSL.name("build_name"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.build_meta.created_at</code>.
     */
    public final TableField<BuildMetaRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private BuildMeta(Name alias, Table<BuildMetaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BuildMeta(Name alias, Table<BuildMetaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.build_meta</code> table reference
     */
    public BuildMeta(String alias) {
        this(DSL.name(alias), BUILD_META);
    }

    /**
     * Create an aliased <code>public.build_meta</code> table reference
     */
    public BuildMeta(Name alias) {
        this(alias, BUILD_META);
    }

    /**
     * Create a <code>public.build_meta</code> table reference
     */
    public BuildMeta() {
        this(DSL.name("build_meta"), null);
    }

    public <O extends Record> BuildMeta(Table<O> path, ForeignKey<O, BuildMetaRecord> childPath, InverseForeignKey<O, BuildMetaRecord> parentPath) {
        super(path, childPath, parentPath, BUILD_META);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BuildMetaPath extends BuildMeta implements Path<BuildMetaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BuildMetaPath(Table<O> path, ForeignKey<O, BuildMetaRecord> childPath, InverseForeignKey<O, BuildMetaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BuildMetaPath(Name alias, Table<BuildMetaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BuildMetaPath as(String alias) {
            return new BuildMetaPath(DSL.name(alias), this);
        }

        @Override
        public BuildMetaPath as(Name alias) {
            return new BuildMetaPath(alias, this);
        }

        @Override
        public BuildMetaPath as(Table<?> alias) {
            return new BuildMetaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BUILD_META_NAME);
    }

    @Override
    public Identity<BuildMetaRecord, Integer> getIdentity() {
        return (Identity<BuildMetaRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BuildMetaRecord> getPrimaryKey() {
        return Keys.BUILD_META_PKEY;
    }

    private transient BuildVersionPath _buildVersion;

    /**
     * Get the implicit to-many join path to the
     * <code>public.build_version</code> table
     */
    public BuildVersionPath buildVersion() {
        if (_buildVersion == null)
            _buildVersion = new BuildVersionPath(this, null, Keys.BUILD_VERSION__BUILD_VERSION_BUILD_META_ID_FKEY.getInverseKey());

        return _buildVersion;
    }

    @Override
    public BuildMeta as(String alias) {
        return new BuildMeta(DSL.name(alias), this);
    }

    @Override
    public BuildMeta as(Name alias) {
        return new BuildMeta(alias, this);
    }

    @Override
    public BuildMeta as(Table<?> alias) {
        return new BuildMeta(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildMeta rename(String name) {
        return new BuildMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildMeta rename(Name name) {
        return new BuildMeta(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildMeta rename(Table<?> name) {
        return new BuildMeta(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta where(Condition condition) {
        return new BuildMeta(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildMeta where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildMeta where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildMeta where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildMeta where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildMeta whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
