/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.readutf.buildformat.postgres.jooq.Indexes;
import org.readutf.buildformat.postgres.jooq.Keys;
import org.readutf.buildformat.postgres.jooq.Public;
import org.readutf.buildformat.postgres.jooq.tables.BuildVersion.BuildVersionPath;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildSupportedFormatsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildSupportedFormats extends TableImpl<BuildSupportedFormatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.build_supported_formats</code>
     */
    public static final BuildSupportedFormats BUILD_SUPPORTED_FORMATS = new BuildSupportedFormats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BuildSupportedFormatsRecord> getRecordType() {
        return BuildSupportedFormatsRecord.class;
    }

    /**
     * The column <code>public.build_supported_formats.id</code>.
     */
    public final TableField<BuildSupportedFormatsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.build_supported_formats.build_version_id</code>.
     */
    public final TableField<BuildSupportedFormatsRecord, Integer> BUILD_VERSION_ID = createField(DSL.name("build_version_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.build_supported_formats.format_name</code>.
     */
    public final TableField<BuildSupportedFormatsRecord, String> FORMAT_NAME = createField(DSL.name("format_name"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private BuildSupportedFormats(Name alias, Table<BuildSupportedFormatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BuildSupportedFormats(Name alias, Table<BuildSupportedFormatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.build_supported_formats</code> table
     * reference
     */
    public BuildSupportedFormats(String alias) {
        this(DSL.name(alias), BUILD_SUPPORTED_FORMATS);
    }

    /**
     * Create an aliased <code>public.build_supported_formats</code> table
     * reference
     */
    public BuildSupportedFormats(Name alias) {
        this(alias, BUILD_SUPPORTED_FORMATS);
    }

    /**
     * Create a <code>public.build_supported_formats</code> table reference
     */
    public BuildSupportedFormats() {
        this(DSL.name("build_supported_formats"), null);
    }

    public <O extends Record> BuildSupportedFormats(Table<O> path, ForeignKey<O, BuildSupportedFormatsRecord> childPath, InverseForeignKey<O, BuildSupportedFormatsRecord> parentPath) {
        super(path, childPath, parentPath, BUILD_SUPPORTED_FORMATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BuildSupportedFormatsPath extends BuildSupportedFormats implements Path<BuildSupportedFormatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BuildSupportedFormatsPath(Table<O> path, ForeignKey<O, BuildSupportedFormatsRecord> childPath, InverseForeignKey<O, BuildSupportedFormatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BuildSupportedFormatsPath(Name alias, Table<BuildSupportedFormatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BuildSupportedFormatsPath as(String alias) {
            return new BuildSupportedFormatsPath(DSL.name(alias), this);
        }

        @Override
        public BuildSupportedFormatsPath as(Name alias) {
            return new BuildSupportedFormatsPath(alias, this);
        }

        @Override
        public BuildSupportedFormatsPath as(Table<?> alias) {
            return new BuildSupportedFormatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BUILD_SUPPORTED_FORMATS_VERSION_ID_FORMAT_NAME);
    }

    @Override
    public Identity<BuildSupportedFormatsRecord, Integer> getIdentity() {
        return (Identity<BuildSupportedFormatsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BuildSupportedFormatsRecord> getPrimaryKey() {
        return Keys.BUILD_SUPPORTED_FORMATS_PKEY;
    }

    @Override
    public List<ForeignKey<BuildSupportedFormatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BUILD_SUPPORTED_FORMATS__BUILD_SUPPORTED_FORMATS_BUILD_VERSION_ID_FKEY);
    }

    private transient BuildVersionPath _buildVersion;

    /**
     * Get the implicit join path to the <code>public.build_version</code>
     * table.
     */
    public BuildVersionPath buildVersion() {
        if (_buildVersion == null)
            _buildVersion = new BuildVersionPath(this, Keys.BUILD_SUPPORTED_FORMATS__BUILD_SUPPORTED_FORMATS_BUILD_VERSION_ID_FKEY, null);

        return _buildVersion;
    }

    @Override
    public BuildSupportedFormats as(String alias) {
        return new BuildSupportedFormats(DSL.name(alias), this);
    }

    @Override
    public BuildSupportedFormats as(Name alias) {
        return new BuildSupportedFormats(alias, this);
    }

    @Override
    public BuildSupportedFormats as(Table<?> alias) {
        return new BuildSupportedFormats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildSupportedFormats rename(String name) {
        return new BuildSupportedFormats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildSupportedFormats rename(Name name) {
        return new BuildSupportedFormats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildSupportedFormats rename(Table<?> name) {
        return new BuildSupportedFormats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats where(Condition condition) {
        return new BuildSupportedFormats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildSupportedFormats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildSupportedFormats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildSupportedFormats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildSupportedFormats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildSupportedFormats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
