/*
 * This file is generated by jOOQ.
 */
package org.readutf.buildformat.postgres.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.readutf.buildformat.postgres.jooq.Indexes;
import org.readutf.buildformat.postgres.jooq.Keys;
import org.readutf.buildformat.postgres.jooq.Public;
import org.readutf.buildformat.postgres.jooq.tables.BuildMeta.BuildMetaPath;
import org.readutf.buildformat.postgres.jooq.tables.BuildSupportedFormats.BuildSupportedFormatsPath;
import org.readutf.buildformat.postgres.jooq.tables.records.BuildVersionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BuildVersion extends TableImpl<BuildVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.build_version</code>
     */
    public static final BuildVersion BUILD_VERSION = new BuildVersion();

    /**
     * The class holding records for this typeReference
     */
    @Override
    public Class<BuildVersionRecord> getRecordType() {
        return BuildVersionRecord.class;
    }

    /**
     * The column <code>public.build_version.id</code>.
     */
    public final TableField<BuildVersionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.build_version.build_meta_id</code>.
     */
    public final TableField<BuildVersionRecord, Integer> BUILD_META_ID = createField(DSL.name("build_meta_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.build_version.version_number</code>.
     */
    public final TableField<BuildVersionRecord, Integer> VERSION_NUMBER = createField(DSL.name("version_number"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.build_version.checksum</code>.
     */
    public final TableField<BuildVersionRecord, Integer> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.build_version.metadata</code>.
     */
    public final TableField<BuildVersionRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false), this, "");

    private BuildVersion(Name alias, Table<BuildVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BuildVersion(Name alias, Table<BuildVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.build_version</code> table reference
     */
    public BuildVersion(String alias) {
        this(DSL.name(alias), BUILD_VERSION);
    }

    /**
     * Create an aliased <code>public.build_version</code> table reference
     */
    public BuildVersion(Name alias) {
        this(alias, BUILD_VERSION);
    }

    /**
     * Create a <code>public.build_version</code> table reference
     */
    public BuildVersion() {
        this(DSL.name("build_version"), null);
    }

    public <O extends Record> BuildVersion(Table<O> path, ForeignKey<O, BuildVersionRecord> childPath, InverseForeignKey<O, BuildVersionRecord> parentPath) {
        super(path, childPath, parentPath, BUILD_VERSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BuildVersionPath extends BuildVersion implements Path<BuildVersionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BuildVersionPath(Table<O> path, ForeignKey<O, BuildVersionRecord> childPath, InverseForeignKey<O, BuildVersionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BuildVersionPath(Name alias, Table<BuildVersionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BuildVersionPath as(String alias) {
            return new BuildVersionPath(DSL.name(alias), this);
        }

        @Override
        public BuildVersionPath as(Name alias) {
            return new BuildVersionPath(alias, this);
        }

        @Override
        public BuildVersionPath as(Table<?> alias) {
            return new BuildVersionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BUILD_VERSION_META_ID_VERSION_NUMBER);
    }

    @Override
    public Identity<BuildVersionRecord, Integer> getIdentity() {
        return (Identity<BuildVersionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BuildVersionRecord> getPrimaryKey() {
        return Keys.BUILD_VERSION_PKEY;
    }

    @Override
    public List<ForeignKey<BuildVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BUILD_VERSION__BUILD_VERSION_BUILD_META_ID_FKEY);
    }

    private transient BuildMetaPath _buildMeta;

    /**
     * Get the implicit join path to the <code>public.build_meta</code> table.
     */
    public BuildMetaPath buildMeta() {
        if (_buildMeta == null)
            _buildMeta = new BuildMetaPath(this, Keys.BUILD_VERSION__BUILD_VERSION_BUILD_META_ID_FKEY, null);

        return _buildMeta;
    }

    private transient BuildSupportedFormatsPath _buildSupportedFormats;

    /**
     * Get the implicit to-many join path to the
     * <code>public.build_supported_formats</code> table
     */
    public BuildSupportedFormatsPath buildSupportedFormats() {
        if (_buildSupportedFormats == null)
            _buildSupportedFormats = new BuildSupportedFormatsPath(this, null, Keys.BUILD_SUPPORTED_FORMATS__BUILD_SUPPORTED_FORMATS_BUILD_VERSION_ID_FKEY.getInverseKey());

        return _buildSupportedFormats;
    }

    @Override
    public BuildVersion as(String alias) {
        return new BuildVersion(DSL.name(alias), this);
    }

    @Override
    public BuildVersion as(Name alias) {
        return new BuildVersion(alias, this);
    }

    @Override
    public BuildVersion as(Table<?> alias) {
        return new BuildVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildVersion rename(String name) {
        return new BuildVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildVersion rename(Name name) {
        return new BuildVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BuildVersion rename(Table<?> name) {
        return new BuildVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion where(Condition condition) {
        return new BuildVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BuildVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BuildVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
